### PR TITLE
[Component with its own class name as service type] LPS-198452 Refactor DeepPaginationConfigurationWrapper component

### PR DESCRIPTION
**Pull request by Valmir-unicap**

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:search

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:report:2488214118

**Comment by Valmir-unicap** [comment]
ci:help

**Comment by Valmir-unicap** [comment]
ci:report:2488211654

**Comment by GinsonRen** [comment]
@Valmir-unicap @dantewang Here is the performance diff test results, there is no regression

**Pull request closed without merging**
